[project]
name = "launcher"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "akirakawashi", email = "mr.oldman.23@gmail.com"},
]
dependencies = ["pywebview>=6.1", "requests>=2.28", "pyinstaller>=6.19.0"]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
